[package]
name = "xt-stcar-device-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
rustix = { version = "=1.1.4", features = ["fs", "event", "termios"] }

[dev-dependencies]
rustix = { version = "=1.1.4", features = ["pty"] }
tempfile.workspace = true

[lints]
workspace = true
